### ISSUE TITLE
Replace  ffdhe4096.pem with a derivation

### ISSUE THREAD

**Issue by fooker** [hackint/nixos-config#13]
It's not clear where `ffdhe4096.pem` is coming from. Downloading this from a well-known source should clarify this.

**Comment by mweinelt** [comment]
https://datatracker.ietf.org/doc/html/rfc7919#appendix-A.3

**Comment by mweinelt** [comment]
Maybe it makes sense to drop Diffie-Hellman altogether and move to the "modern compatibility"?

https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility
